# Generated by Django 4.2.3 on 2023-09-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('foundation', 'Foundation'), ('first_year', 'First Year'), ('second_year', 'Second Year'), ('advanced', 'Advanced'), ('bachelor', 'Bachelor')], max_length=255),
        ),
    ]
