# Generated by Django 4.2.3 on 2023-09-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.SmallIntegerField(blank=True, default=3, null=True),
        ),
    ]
