# Generated by Django 4.2.3 on 2023-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_course_specialization_course_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='specialization',
        ),
        migrations.AddField(
            model_name='course',
            name='specialization',
            field=models.ManyToManyField(null=True, to='main.specialization'),
        ),
    ]
