# Generated by Django 4.2.3 on 2023-10-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_course_specialization_course_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='sp_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.ManyToManyField(to='main.specialization'),
        ),
    ]
